# Generated by Django 3.1.7 on 2021-03-29 17:36

import channel.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(default='No description')),
                ('followers', models.IntegerField(default=0)),
                ('banner', models.ImageField(default='posts/defaultBanner.jpg', upload_to=channel.models.upload_to, verbose_name='BannerImage')),
                ('avatar', models.ImageField(default='posts/defaultAvatar.jpg', upload_to=channel.models.upload_to, verbose_name='Avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
