# Generated by Django 3.1.7 on 2021-03-29 17:56

import channel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='banner',
            field=models.ImageField(default='posts/defaultBanner.jpg', upload_to=channel.models.upload_to_b, verbose_name='BannerImage'),
        ),
    ]
