# Generated by Django 3.1.7 on 2021-03-29 19:48

import channel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_auto_20210329_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='avatar',
            field=models.ImageField(default='channel/avatar/defaultAvatar.jpg', upload_to=channel.models.upload_to, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='banner',
            field=models.ImageField(default='channel/banner/defaultBanner.jpg', upload_to=channel.models.upload_to_b, verbose_name='BannerImage'),
        ),
    ]
