# Generated by Django 3.1.7 on 2021-04-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_auto_20210330_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='slug',
            field=models.SlugField(default='channel_name', max_length=250),
        ),
    ]
