# Generated by Django 3.1.7 on 2021-04-02 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0008_channel_subscribedchannels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='subscribedChannels',
            new_name='followedChannels',
        ),
    ]
