# Generated by Django 3.1.7 on 2021-04-03 21:01

from django.db import migrations, models
import django.db.models.deletion
import user_post.models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0010_auto_20210403_0012'),
        ('user_post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='author',
        ),
        migrations.AddField(
            model_name='userpost',
            name='banner',
            field=models.ImageField(null=True, upload_to=user_post.models.upload_to, verbose_name='UserPostImage'),
        ),
        migrations.AddField(
            model_name='userpost',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='channel.channel'),
        ),
        migrations.AddField(
            model_name='userpost',
            name='slug',
            field=models.SlugField(default='channel_name', max_length=250, unique=True),
        ),
    ]
