# Generated by Django 3.1.7 on 2021-04-03 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_post', '0002_auto_20210404_0231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='banner',
            new_name='image',
        ),
    ]
