# Generated by Django 3.1.7 on 2021-04-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_post', '0003_auto_20210404_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
