# Generated by Django 3.1.7 on 2021-04-05 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_post', '0004_auto_20210405_0119'),
        ('channel', '0010_auto_20210403_0012'),
        ('multimedia', '0001_initial'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='audio_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multimedia.audio'),
        ),
        migrations.AddField(
            model_name='comment',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='channel.channel'),
        ),
        migrations.AddField(
            model_name='comment',
            name='userPost_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_post.userpost'),
        ),
        migrations.AddField(
            model_name='comment',
            name='video_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multimedia.video'),
        ),
    ]
